name: absensi_digital
description: A Flutter app for digital attendance using front camera QR scan
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  mobile_scanner: ^2.0.0
  provider: ^6.0.0
  http: ^0.13.0
  sqflite: ^2.2.8
  path_provider: ^2.0.15
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
